### PR TITLE
Update game.js

### PR DESCRIPTION
**Pull request by RuralAir**
Fixed up some buggy graphics and prepped to add @conner1115's graphics.

### CODE REVIEW

**Comment by IroncladDev** [comment]
This is me, Leviathan responding through email.

You can merge pull requests yourself?

**Comment by RuralAir** [comment]
Ahh, I see your confusion. I can send and merge pull requests *into my own
forked copy* of your code. I wanted to see if it would increase HTML update
speed.

Warmly, Christopher

**Comment by IroncladDev** [comment]
That's cool

**Comment by IroncladDev** [comment]
Are you just inactive on KA or have you been banned?
I guess we've just not been working on the LOTR game lately.
The reason why I'm not is that I've been working on a TD.

**Comment by RuralAir** [comment]
I'm inactive on KA for a while as schoolwork picks up. Worst case scenario,
I'll be back on summer break. Best case scenario, I'll be back as soon as I
get a big paper written.

Osu, Christopher

**Comment by IroncladDev** [comment]
Okay.  Looking forward to your return to KA.

**Pull request merged**
